org.gradle.jvmargs=-Xmx2560m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=2
android.useAndroidX=true
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=/tmp/opencode/aapt2
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=37.0
